export interface ProductVariant {
  color?: string;
  capacity?: string;
  price: number;
  originalPrice: number;
}

export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  image: string;
  category: string;
  description: string;
  features: string[];
  variants?: ProductVariant[];
  hasVariants?: boolean;
}

export const products: Product[] = [
  // === SMARTPHONES - Latest 2025 Models from GSMArena ===
  // iPhone 17 Pro Max with variants (Pixmania data)
  {
    id: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    price: 1717,
    originalPrice: 2099,
    discount: 18,
    image: '/assets/stock_images/iphone_17_pro_max_si_1febe1b9.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.9" ProMotion Display',
    features: ['Apple A19 Pro chip', '6.9" LTPO OLED 120Hz', '48MP triple camera', 'Ceramic Shield 2', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Silver', capacity: '256GB', price: 1717, originalPrice: 2099 },
      { color: 'Silver', capacity: '512GB', price: 2052, originalPrice: 2499 },
      { color: 'Silver', capacity: '1TB', price: 2332, originalPrice: 2799 },
      { color: 'Silver', capacity: '2TB', price: 2890, originalPrice: 3499 },
      { color: 'Cosmic Orange', capacity: '256GB', price: 1717, originalPrice: 2099 },
      { color: 'Cosmic Orange', capacity: '512GB', price: 2052, originalPrice: 2499 },
      { color: 'Cosmic Orange', capacity: '1TB', price: 2333, originalPrice: 2799 },
      { color: 'Cosmic Orange', capacity: '2TB', price: 2918, originalPrice: 3499 },
      { color: 'Deep Blue', capacity: '256GB', price: 1736, originalPrice: 2099 },
      { color: 'Deep Blue', capacity: '512GB', price: 2052, originalPrice: 2499 },
      { color: 'Deep Blue', capacity: '1TB', price: 2332, originalPrice: 2799 },
      { color: 'Deep Blue', capacity: '2TB', price: 2863, originalPrice: 3499 },
    ]
  },
  // iPhone 17 Pro with variants (Pixmania data)
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    price: 1469,
    originalPrice: 1799,
    discount: 18,
    image: '/assets/stock_images/iphone_17_pro_silver_a2fb0732.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.3" ProMotion Display',
    features: ['Apple A19 Pro chip', '6.3" LTPO OLED 120Hz', '48MP triple camera', 'Aluminum frame', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Silver', capacity: '256GB', price: 1539, originalPrice: 1899 },
      { color: 'Silver', capacity: '512GB', price: 1799, originalPrice: 2199 },
      { color: 'Silver', capacity: '1TB', price: 2099, originalPrice: 2499 },
      { color: 'Cosmic Orange', capacity: '256GB', price: 1502, originalPrice: 1899 },
      { color: 'Cosmic Orange', capacity: '512GB', price: 1799, originalPrice: 2199 },
      { color: 'Cosmic Orange', capacity: '1TB', price: 2099, originalPrice: 2499 },
      { color: 'Deep Blue', capacity: '256GB', price: 1469, originalPrice: 1899 },
      { color: 'Deep Blue', capacity: '512GB', price: 1799, originalPrice: 2199 },
      { color: 'Deep Blue', capacity: '1TB', price: 2099, originalPrice: 2499 },
    ]
  },
  // iPhone Air with variants
  {
    id: 'iphone-air',
    name: 'iPhone Air',
    price: 999,
    originalPrice: 1199,
    discount: 17,
    image: '/assets/stock_images/apple_iphone_air_ult_d3cfc5fc.jpg',
    category: 'smartphones',
    description: 'From 256GB - Ultra-thin 5.6mm design',
    features: ['Apple A19 Pro chip', '6.5" LTPO OLED 120Hz', '48MP camera', '5.6mm thickness', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Space Black', capacity: '256GB', price: 999, originalPrice: 1199 },
      { color: 'Space Black', capacity: '512GB', price: 1199, originalPrice: 1399 },
      { color: 'Space Black', capacity: '1TB', price: 1499, originalPrice: 1699 },
      { color: 'Cloud White', capacity: '256GB', price: 999, originalPrice: 1199 },
      { color: 'Cloud White', capacity: '512GB', price: 1199, originalPrice: 1399 },
      { color: 'Cloud White', capacity: '1TB', price: 1499, originalPrice: 1699 },
      { color: 'Light Gold', capacity: '256GB', price: 999, originalPrice: 1199 },
      { color: 'Light Gold', capacity: '512GB', price: 1199, originalPrice: 1399 },
      { color: 'Light Gold', capacity: '1TB', price: 1499, originalPrice: 1699 },
      { color: 'Sky Blue', capacity: '256GB', price: 999, originalPrice: 1199 },
      { color: 'Sky Blue', capacity: '512GB', price: 1199, originalPrice: 1399 },
      { color: 'Sky Blue', capacity: '1TB', price: 1499, originalPrice: 1699 },
    ]
  },
  // iPhone 17 with variants (Pixmania data)
  {
    id: 'iphone-17',
    name: 'iPhone 17',
    price: 1136,
    originalPrice: 1399,
    discount: 19,
    image: '/assets/stock_images/iphone_17_black_colo_3e2b53d1.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.3" Display',
    features: ['Apple A19 chip', '6.3" LTPO OLED 120Hz', '48MP dual camera', 'All-day battery', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 1136, originalPrice: 1399 },
      { color: 'Black', capacity: '512GB', price: 1464, originalPrice: 1699 },
      { color: 'White', capacity: '256GB', price: 1148, originalPrice: 1399 },
      { color: 'White', capacity: '512GB', price: 1464, originalPrice: 1699 },
      { color: 'Mist Blue', capacity: '256GB', price: 1136, originalPrice: 1399 },
      { color: 'Mist Blue', capacity: '512GB', price: 1464, originalPrice: 1699 },
      { color: 'Sage', capacity: '256GB', price: 1136, originalPrice: 1399 },
      { color: 'Sage', capacity: '512GB', price: 1464, originalPrice: 1699 },
      { color: 'Lavender', capacity: '256GB', price: 1136, originalPrice: 1399 },
      { color: 'Lavender', capacity: '512GB', price: 1464, originalPrice: 1699 },
    ]
  },
  // iPhone 16 Pro Max with variants
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    price: 929,
    originalPrice: 1099,
    discount: 15,
    image: '/attached_assets/smartphones/iphone-16-pro-max.jpg',
    category: 'smartphones',
    description: 'From 256GB - Previous Gen Flagship',
    features: ['Apple A18 Pro chip', '6.9" LTPO OLED 120Hz', '48MP triple camera', 'Titanium design', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black Titanium', capacity: '256GB', price: 929, originalPrice: 1099 },
      { color: 'Black Titanium', capacity: '512GB', price: 1099, originalPrice: 1299 },
      { color: 'Black Titanium', capacity: '1TB', price: 1399, originalPrice: 1599 },
      { color: 'White Titanium', capacity: '256GB', price: 929, originalPrice: 1099 },
      { color: 'White Titanium', capacity: '512GB', price: 1099, originalPrice: 1299 },
      { color: 'White Titanium', capacity: '1TB', price: 1399, originalPrice: 1599 },
      { color: 'Natural Titanium', capacity: '256GB', price: 929, originalPrice: 1099 },
      { color: 'Natural Titanium', capacity: '512GB', price: 1099, originalPrice: 1299 },
      { color: 'Natural Titanium', capacity: '1TB', price: 1399, originalPrice: 1599 },
      { color: 'Desert Titanium', capacity: '256GB', price: 929, originalPrice: 1099 },
      { color: 'Desert Titanium', capacity: '512GB', price: 1099, originalPrice: 1299 },
      { color: 'Desert Titanium', capacity: '1TB', price: 1399, originalPrice: 1599 },
    ]
  },
  // Samsung Galaxy S25 Ultra with variants (Pixmania data)
  {
    id: 'samsung-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    price: 948,
    originalPrice: 1472,
    discount: 36,
    image: '/assets/stock_images/samsung_galaxy_s25_u_1c4ee831.jpg',
    category: 'smartphones',
    description: 'From 256GB - S Pen included',
    features: ['Snapdragon 8 Elite', '6.9" Dynamic AMOLED 120Hz', '200MP quad camera', 'S Pen stylus', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Titanium Blue', capacity: '256GB', price: 989, originalPrice: 1539 },
      { color: 'Titanium Blue', capacity: '512GB', price: 1089, originalPrice: 1599 },
      { color: 'Titanium Blue', capacity: '1TB', price: 1299, originalPrice: 1799 },
      { color: 'Titanium Black', capacity: '256GB', price: 948, originalPrice: 1472 },
      { color: 'Titanium Black', capacity: '512GB', price: 1089, originalPrice: 1599 },
      { color: 'Titanium Black', capacity: '1TB', price: 1299, originalPrice: 1799 },
      { color: 'Titanium White Silver', capacity: '256GB', price: 960, originalPrice: 1472 },
      { color: 'Titanium White Silver', capacity: '512GB', price: 1089, originalPrice: 1599 },
      { color: 'Titanium White Silver', capacity: '1TB', price: 1299, originalPrice: 1799 },
      { color: 'Titanium Gray', capacity: '256GB', price: 960, originalPrice: 1472 },
      { color: 'Titanium Gray', capacity: '512GB', price: 1089, originalPrice: 1599 },
      { color: 'Titanium Gray', capacity: '1TB', price: 1299, originalPrice: 1799 },
    ]
  },
  // Samsung Galaxy S25 with variants (Pixmania data)
  {
    id: 'samsung-s25',
    name: 'Samsung Galaxy S25',
    price: 578,
    originalPrice: 949,
    discount: 39,
    image: '/assets/stock_images/samsung_galaxy_s25_n_037e580a.jpg',
    category: 'smartphones',
    description: 'From 128GB - Compact flagship',
    features: ['Snapdragon 8 Elite', '6.2" Dynamic AMOLED 120Hz', '50MP triple camera', 'Armor aluminum frame', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Blue', capacity: '128GB', price: 595, originalPrice: 949 },
      { color: 'Blue', capacity: '256GB', price: 649, originalPrice: 959 },
      { color: 'Blue', capacity: '512GB', price: 812, originalPrice: 1079 },
      { color: 'Mint', capacity: '128GB', price: 603, originalPrice: 899 },
      { color: 'Mint', capacity: '256GB', price: 670, originalPrice: 959 },
      { color: 'Mint', capacity: '512GB', price: 812, originalPrice: 1079 },
      { color: 'Navy', capacity: '128GB', price: 616, originalPrice: 899 },
      { color: 'Navy', capacity: '256GB', price: 646, originalPrice: 959 },
      { color: 'Navy', capacity: '512GB', price: 799, originalPrice: 1079 },
      { color: 'Silver', capacity: '128GB', price: 578, originalPrice: 899 },
      { color: 'Silver', capacity: '256GB', price: 665, originalPrice: 959 },
      { color: 'Silver', capacity: '512GB', price: 842, originalPrice: 1079 },
      { color: 'Black', capacity: '128GB', price: 654, originalPrice: 899 },
      { color: 'Black', capacity: '256GB', price: 692, originalPrice: 959 },
      { color: 'Black', capacity: '512GB', price: 893, originalPrice: 1079 },
    ]
  },
  // Samsung Galaxy Z Fold7 with variants
  {
    id: 'samsung-z-fold7',
    name: 'Samsung Galaxy Z Fold7',
    price: 1799,
    originalPrice: 2099,
    discount: 14,
    image: '/attached_assets/smartphones/samsung-z-fold7.jpg',
    category: 'smartphones',
    description: 'From 256GB - Foldable flagship',
    features: ['Snapdragon 8 Elite', '8.0" foldable AMOLED', '200MP camera', 'Ultra-thin design', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Blue Shadow', capacity: '256GB', price: 1799, originalPrice: 2099 },
      { color: 'Blue Shadow', capacity: '512GB', price: 1999, originalPrice: 2299 },
      { color: 'Blue Shadow', capacity: '1TB', price: 2299, originalPrice: 2599 },
      { color: 'Silver Shadow', capacity: '256GB', price: 1799, originalPrice: 2099 },
      { color: 'Silver Shadow', capacity: '512GB', price: 1999, originalPrice: 2299 },
      { color: 'Silver Shadow', capacity: '1TB', price: 2299, originalPrice: 2599 },
      { color: 'Jet Black', capacity: '256GB', price: 1799, originalPrice: 2099 },
      { color: 'Jet Black', capacity: '512GB', price: 1999, originalPrice: 2299 },
      { color: 'Jet Black', capacity: '1TB', price: 2299, originalPrice: 2599 },
      { color: 'Mint', capacity: '256GB', price: 1799, originalPrice: 2099 },
      { color: 'Mint', capacity: '512GB', price: 1999, originalPrice: 2299 },
      { color: 'Mint', capacity: '1TB', price: 2299, originalPrice: 2599 },
    ]
  },
  // Samsung Galaxy Z Flip7 with variants
  {
    id: 'samsung-z-flip7',
    name: 'Samsung Galaxy Z Flip7',
    price: 879,
    originalPrice: 1049,
    discount: 16,
    image: '/attached_assets/smartphones/samsung-z-flip7.jpg',
    category: 'smartphones',
    description: 'From 256GB - Compact foldable',
    features: ['Exynos 2500', '6.9" foldable display', '50MP dual camera', 'Compact design', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Blue Shadow', capacity: '256GB', price: 879, originalPrice: 1049 },
      { color: 'Blue Shadow', capacity: '512GB', price: 1049, originalPrice: 1249 },
      { color: 'Jet Black', capacity: '256GB', price: 879, originalPrice: 1049 },
      { color: 'Jet Black', capacity: '512GB', price: 1049, originalPrice: 1249 },
      { color: 'Coral Red', capacity: '256GB', price: 879, originalPrice: 1049 },
      { color: 'Coral Red', capacity: '512GB', price: 1049, originalPrice: 1249 },
      { color: 'Mint', capacity: '256GB', price: 879, originalPrice: 1049 },
      { color: 'Mint', capacity: '512GB', price: 1049, originalPrice: 1249 },
    ]
  },
  // Google Pixel 10 Pro with variants
  {
    id: 'google-pixel-10-pro',
    name: 'Google Pixel 10 Pro',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/assets/stock_images/google_pixel_10_pro__7df7241d.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.3" Super Actua Display',
    features: ['Google Tensor G5', '6.3" LTPO OLED 120Hz', '50MP + 48MP cameras', '7 years updates', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Obsidian', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Obsidian', capacity: '256GB', price: 999, originalPrice: 1099 },
      { color: 'Obsidian', capacity: '512GB', price: 1199, originalPrice: 1299 },
      { color: 'Obsidian', capacity: '1TB', price: 1449, originalPrice: 1599 },
      { color: 'Porcelain', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Porcelain', capacity: '256GB', price: 999, originalPrice: 1099 },
      { color: 'Porcelain', capacity: '512GB', price: 1199, originalPrice: 1299 },
      { color: 'Porcelain', capacity: '1TB', price: 1449, originalPrice: 1599 },
      { color: 'Jade', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Jade', capacity: '256GB', price: 999, originalPrice: 1099 },
      { color: 'Jade', capacity: '512GB', price: 1199, originalPrice: 1299 },
      { color: 'Moonstone', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Moonstone', capacity: '256GB', price: 999, originalPrice: 1099 },
      { color: 'Moonstone', capacity: '512GB', price: 1199, originalPrice: 1299 },
    ]
  },
  // OnePlus 13 with variants
  {
    id: 'oneplus-13',
    name: 'OnePlus 13',
    price: 749,
    originalPrice: 899,
    discount: 17,
    image: '/assets/stock_images/oneplus_13_smartphon_60b38945.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.82" AMOLED Display',
    features: ['Snapdragon 8 Elite', 'Triple 50MP cameras', '6000mAh + 100W charging', 'IP68/IP69', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black Eclipse', capacity: '256GB', price: 749, originalPrice: 899 },
      { color: 'Black Eclipse', capacity: '512GB', price: 899, originalPrice: 1049 },
      { color: 'Black Eclipse', capacity: '1TB', price: 1099, originalPrice: 1249 },
      { color: 'Arctic Dawn', capacity: '256GB', price: 749, originalPrice: 899 },
      { color: 'Arctic Dawn', capacity: '512GB', price: 899, originalPrice: 1049 },
      { color: 'Arctic Dawn', capacity: '1TB', price: 1099, originalPrice: 1249 },
      { color: 'Midnight Ocean', capacity: '256GB', price: 749, originalPrice: 899 },
      { color: 'Midnight Ocean', capacity: '512GB', price: 899, originalPrice: 1049 },
      { color: 'Midnight Ocean', capacity: '1TB', price: 1099, originalPrice: 1249 },
    ]
  },
  // Xiaomi 15 with variants
  {
    id: 'xiaomi-15',
    name: 'Xiaomi 15',
    price: 649,
    originalPrice: 749,
    discount: 13,
    image: '/assets/stock_images/xiaomi_15_standard_s_12e3b53c.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.36" LTPO AMOLED',
    features: ['Snapdragon 8 Elite', 'Triple 50MP Leica', '5240mAh + 90W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 649, originalPrice: 749 },
      { color: 'Black', capacity: '512GB', price: 799, originalPrice: 899 },
      { color: 'Black', capacity: '1TB', price: 999, originalPrice: 1099 },
      { color: 'White', capacity: '256GB', price: 649, originalPrice: 749 },
      { color: 'White', capacity: '512GB', price: 799, originalPrice: 899 },
      { color: 'White', capacity: '1TB', price: 999, originalPrice: 1099 },
      { color: 'Liquid Silver', capacity: '256GB', price: 649, originalPrice: 749 },
      { color: 'Liquid Silver', capacity: '512GB', price: 799, originalPrice: 899 },
      { color: 'Lilac', capacity: '256GB', price: 649, originalPrice: 749 },
      { color: 'Lilac', capacity: '512GB', price: 799, originalPrice: 899 },
    ]
  },
  // Xiaomi 15 Ultra with variants
  {
    id: 'xiaomi-15-ultra',
    name: 'Xiaomi 15 Ultra',
    price: 1349,
    originalPrice: 1499,
    discount: 10,
    image: '/assets/stock_images/xiaomi_15_ultra_smar_fa0cfae3.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.73" LTPO AMOLED',
    features: ['Snapdragon 8 Elite', '200MP Leica telephoto', '6000mAh + 90W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 1349, originalPrice: 1499 },
      { color: 'Black', capacity: '512GB', price: 1549, originalPrice: 1699 },
      { color: 'Black', capacity: '1TB', price: 1799, originalPrice: 1999 },
      { color: 'White', capacity: '256GB', price: 1349, originalPrice: 1499 },
      { color: 'White', capacity: '512GB', price: 1549, originalPrice: 1699 },
      { color: 'White', capacity: '1TB', price: 1799, originalPrice: 1999 },
      { color: 'Silver Chrome', capacity: '512GB', price: 1549, originalPrice: 1699 },
      { color: 'Silver Chrome', capacity: '1TB', price: 1799, originalPrice: 1999 },
    ]
  },
  // Google Pixel 9 Pro XL with variants (2024)
  {
    id: 'google-pixel-9-pro-xl',
    name: 'Google Pixel 9 Pro XL',
    price: 989,
    originalPrice: 1099,
    discount: 10,
    image: '/attached_assets/smartphones/google-pixel-9-pro-xl.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.8" Super Actua Display',
    features: ['Google Tensor G4', '6.8" LTPO OLED 120Hz', '50MP triple camera', '7 years updates', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Obsidian', capacity: '128GB', price: 989, originalPrice: 1099 },
      { color: 'Obsidian', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Obsidian', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Obsidian', capacity: '1TB', price: 1529, originalPrice: 1699 },
      { color: 'Porcelain', capacity: '128GB', price: 989, originalPrice: 1099 },
      { color: 'Porcelain', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Porcelain', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Porcelain', capacity: '1TB', price: 1529, originalPrice: 1699 },
      { color: 'Hazel', capacity: '128GB', price: 989, originalPrice: 1099 },
      { color: 'Hazel', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Hazel', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Hazel', capacity: '1TB', price: 1529, originalPrice: 1699 },
    ]
  },
  // Motorola Razr 50 Ultra with variants (2024)
  {
    id: 'motorola-razr-50-ultra',
    name: 'Motorola Razr 50 Ultra',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/attached_assets/smartphones/motorola-razr-50-ultra.jpg',
    category: 'smartphones',
    description: 'From 256GB - Flip Phone with 4.0" External Display',
    features: ['Snapdragon 8s Gen 3', '6.9" Foldable AMOLED 165Hz', '50MP dual camera', 'IPX8 water resistance', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Midnight Blue', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Midnight Blue', capacity: '512GB', price: 1049, originalPrice: 1149 },
      { color: 'Spring Green', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Spring Green', capacity: '512GB', price: 1049, originalPrice: 1149 },
      { color: 'Hot Pink', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Hot Pink', capacity: '512GB', price: 1049, originalPrice: 1149 },
      { color: 'Peach Fuzz', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Peach Fuzz', capacity: '512GB', price: 1049, originalPrice: 1149 },
    ]
  },
  // Poco F6 Pro with variants (2024)
  {
    id: 'poco-f6-pro',
    name: 'Poco F6 Pro',
    price: 324,
    originalPrice: 360,
    discount: 10,
    image: '/attached_assets/smartphones/poco-f6-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - Flagship Killer',
    features: ['Snapdragon 8 Gen 2', '6.67" WQHD+ AMOLED 120Hz', '50MP triple camera', '120W HyperCharge', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 324, originalPrice: 360 },
      { color: 'Black', capacity: '512GB', price: 414, originalPrice: 460 },
      { color: 'Black', capacity: '1TB', price: 540, originalPrice: 600 },
      { color: 'White', capacity: '256GB', price: 324, originalPrice: 360 },
      { color: 'White', capacity: '512GB', price: 414, originalPrice: 460 },
      { color: 'White', capacity: '1TB', price: 540, originalPrice: 600 },
    ]
  },
  // Oppo Find X7 Ultra with variants (2024)
  {
    id: 'oppo-find-x7-ultra',
    name: 'Oppo Find X7 Ultra',
    price: 752,
    originalPrice: 836,
    discount: 10,
    image: '/attached_assets/smartphones/oppo-find-x7-ultra.jpg',
    category: 'smartphones',
    description: 'From 256GB - Quad Main Camera System',
    features: ['Snapdragon 8 Gen 3', '6.82" LTPO AMOLED 120Hz', '50MP quad camera', 'Hasselblad tuning', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Ocean Blue', capacity: '256GB', price: 752, originalPrice: 836 },
      { color: 'Ocean Blue', capacity: '512GB', price: 896, originalPrice: 995 },
      { color: 'Sepia Brown', capacity: '256GB', price: 752, originalPrice: 836 },
      { color: 'Sepia Brown', capacity: '512GB', price: 896, originalPrice: 995 },
      { color: 'Tailored Black', capacity: '256GB', price: 752, originalPrice: 836 },
      { color: 'Tailored Black', capacity: '512GB', price: 896, originalPrice: 995 },
    ]
  },
  // Vivo X100 Pro with variants (2024)
  {
    id: 'vivo-x100-pro',
    name: 'Vivo X100 Pro',
    price: 810,
    originalPrice: 900,
    discount: 10,
    image: '/attached_assets/smartphones/vivo-x100-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - ZEISS Optics',
    features: ['Dimensity 9300', '6.78" LTPO AMOLED 120Hz', '50MP triple ZEISS', '100W fast charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Startrail Blue', capacity: '256GB', price: 810, originalPrice: 900 },
      { color: 'Startrail Blue', capacity: '512GB', price: 945, originalPrice: 1050 },
      { color: 'Startrail Blue', capacity: '1TB', price: 1080, originalPrice: 1200 },
      { color: 'Sunset Orange', capacity: '256GB', price: 810, originalPrice: 900 },
      { color: 'Sunset Orange', capacity: '512GB', price: 945, originalPrice: 1050 },
      { color: 'Sunset Orange', capacity: '1TB', price: 1080, originalPrice: 1200 },
      { color: 'Asteroid Black', capacity: '256GB', price: 810, originalPrice: 900 },
      { color: 'Asteroid Black', capacity: '512GB', price: 945, originalPrice: 1050 },
      { color: 'Asteroid Black', capacity: '1TB', price: 1080, originalPrice: 1200 },
    ]
  },
  // Nothing Phone 3 with variants (2025)
  {
    id: 'nothing-phone-3',
    name: 'Nothing Phone 3',
    price: 719,
    originalPrice: 799,
    discount: 10,
    image: '/attached_assets/smartphones/nothing-phone-3.jpg',
    category: 'smartphones',
    description: 'From 256GB - Glyph Matrix LED Display',
    features: ['Snapdragon 8s Gen 4', '6.67" AMOLED 120Hz', 'Triple 50MP cameras', 'Glyph Matrix (489 LEDs)', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Black', capacity: '512GB', price: 809, originalPrice: 899 },
      { color: 'White', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'White', capacity: '512GB', price: 809, originalPrice: 899 },
    ]
  },
  // Asus ROG Phone 8 Pro with variants (2024)
  {
    id: 'asus-rog-phone-8-pro',
    name: 'Asus ROG Phone 8 Pro',
    price: 1169,
    originalPrice: 1299,
    discount: 10,
    image: '/attached_assets/smartphones/asus-rog-phone-8-pro.jpg',
    category: 'smartphones',
    description: 'From 512GB - Ultimate Gaming Phone',
    features: ['Snapdragon 8 Gen 3', '6.78" AMOLED 165Hz', '50MP gimbal camera', 'AirTrigger controls', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Phantom Black', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Phantom Black', capacity: '1TB', price: 1439, originalPrice: 1599 },
    ]
  },
  // Sony Xperia 1 VI with variants (2024)
  {
    id: 'sony-xperia-1-vi',
    name: 'Sony Xperia 1 VI',
    price: 1259,
    originalPrice: 1399,
    discount: 10,
    image: '/attached_assets/smartphones/sony-xperia-1-vi.jpg',
    category: 'smartphones',
    description: 'From 256GB - Pro Camera & Audio',
    features: ['Snapdragon 8 Gen 3', '6.5" LTPO OLED 120Hz', '48MP Zeiss cameras', '3.5mm headphone jack', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 1259, originalPrice: 1399 },
      { color: 'Black', capacity: '512GB', price: 1439, originalPrice: 1599 },
      { color: 'Platinum Silver', capacity: '256GB', price: 1259, originalPrice: 1399 },
      { color: 'Platinum Silver', capacity: '512GB', price: 1439, originalPrice: 1599 },
    ]
  },
  // Samsung Galaxy A55 with variants (2024)
  {
    id: 'samsung-galaxy-a55',
    name: 'Samsung Galaxy A55 5G',
    price: 305,
    originalPrice: 380,
    discount: 20,
    image: '/attached_assets/smartphones/samsung-galaxy-a55.jpg',
    category: 'smartphones',
    description: 'From 128GB - Premium Mid-Range',
    features: ['Exynos 1480', '6.6" Super AMOLED 120Hz', '50MP OIS camera', 'IP67 water resistance', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Awesome Iceblue', capacity: '128GB', price: 305, originalPrice: 380 },
      { color: 'Awesome Iceblue', capacity: '256GB', price: 360, originalPrice: 450 },
      { color: 'Awesome Navy', capacity: '128GB', price: 305, originalPrice: 380 },
      { color: 'Awesome Navy', capacity: '256GB', price: 360, originalPrice: 450 },
      { color: 'Awesome Lilac', capacity: '128GB', price: 305, originalPrice: 380 },
      { color: 'Awesome Lilac', capacity: '256GB', price: 360, originalPrice: 450 },
      { color: 'Awesome Lemon', capacity: '128GB', price: 305, originalPrice: 380 },
      { color: 'Awesome Lemon', capacity: '256GB', price: 360, originalPrice: 450 },
    ]
  },
  // Google Pixel 8a with variants (2024)
  {
    id: 'google-pixel-8a',
    name: 'Google Pixel 8a',
    price: 449,
    originalPrice: 499,
    discount: 10,
    image: '/attached_assets/smartphones/google-pixel-8a.jpg',
    category: 'smartphones',
    description: 'From 128GB - AI-Powered Camera',
    features: ['Google Tensor G3', '6.1" OLED 120Hz', '64MP camera', '7 years of updates', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Obsidian', capacity: '128GB', price: 449, originalPrice: 499 },
      { color: 'Obsidian', capacity: '256GB', price: 503, originalPrice: 559 },
      { color: 'Porcelain', capacity: '128GB', price: 449, originalPrice: 499 },
      { color: 'Porcelain', capacity: '256GB', price: 503, originalPrice: 559 },
      { color: 'Bay', capacity: '128GB', price: 449, originalPrice: 499 },
      { color: 'Bay', capacity: '256GB', price: 503, originalPrice: 559 },
      { color: 'Aloe', capacity: '128GB', price: 449, originalPrice: 499 },
      { color: 'Aloe', capacity: '256GB', price: 503, originalPrice: 559 },
    ]
  },
  // OnePlus 12R with variants (2024)
  {
    id: 'oneplus-12r',
    name: 'OnePlus 12R',
    price: 449,
    originalPrice: 499,
    discount: 10,
    image: '/attached_assets/smartphones/oneplus-12r.jpg',
    category: 'smartphones',
    description: 'From 128GB - Flagship Killer',
    features: ['Snapdragon 8 Gen 2', '6.78" LTPO AMOLED 120Hz', 'Triple 50MP cameras', '5500mAh + 80W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Cool Blue', capacity: '128GB', price: 449, originalPrice: 499 },
      { color: 'Cool Blue', capacity: '256GB', price: 539, originalPrice: 599 },
      { color: 'Iron Gray', capacity: '128GB', price: 449, originalPrice: 499 },
      { color: 'Iron Gray', capacity: '256GB', price: 539, originalPrice: 599 },
    ]
  },
  // Realme GT 6 with variants (2024)
  {
    id: 'realme-gt-6',
    name: 'Realme GT 6',
    price: 378,
    originalPrice: 420,
    discount: 10,
    image: '/attached_assets/smartphones/realme-gt-6.jpg',
    category: 'smartphones',
    description: 'From 256GB - Gaming Beast',
    features: ['Snapdragon 8s Gen 3', '6.78" AMOLED 120Hz', '50MP Sony LYT-808 OIS', '5500mAh + 120W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Fluid Silver', capacity: '256GB', price: 378, originalPrice: 420 },
      { color: 'Fluid Silver', capacity: '512GB', price: 450, originalPrice: 500 },
      { color: 'Razor Green', capacity: '256GB', price: 378, originalPrice: 420 },
      { color: 'Razor Green', capacity: '512GB', price: 450, originalPrice: 500 },
    ]
  },
  // Motorola Edge 50 Pro with variants (2024)
  {
    id: 'motorola-edge-50-pro',
    name: 'Motorola Edge 50 Pro',
    price: 305,
    originalPrice: 335,
    discount: 9,
    image: '/attached_assets/smartphones/motorola-edge-50-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - Ultra-Fast Charging',
    features: ['Snapdragon 7 Gen 3', '6.7" pOLED 144Hz', '50MP OIS camera', '125W fast charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Luxe Lavender', capacity: '256GB', price: 305, originalPrice: 335 },
      { color: 'Luxe Lavender', capacity: '512GB', price: 342, originalPrice: 380 },
      { color: 'Black Beauty', capacity: '256GB', price: 305, originalPrice: 335 },
      { color: 'Black Beauty', capacity: '512GB', price: 342, originalPrice: 380 },
      { color: 'Moonlight Pearl', capacity: '256GB', price: 305, originalPrice: 335 },
      { color: 'Moonlight Pearl', capacity: '512GB', price: 342, originalPrice: 380 },
    ]
  },
  // Samsung Galaxy S25+ with variants
  {
    id: 'samsung-s25-plus',
    name: 'Samsung Galaxy S25+',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/attached_assets/smartphones/samsung-s25-plus.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.7" QHD+ Display',
    features: ['Snapdragon 8 Elite', '6.7" Dynamic AMOLED 120Hz', '50MP triple camera', 'Gorilla Glass Victus 2', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Navy', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Navy', capacity: '512GB', price: 1099, originalPrice: 1199 },
      { color: 'Icy Blue', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Icy Blue', capacity: '512GB', price: 1099, originalPrice: 1199 },
      { color: 'Mint', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Mint', capacity: '512GB', price: 1099, originalPrice: 1199 },
      { color: 'Silver Shadow', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Silver Shadow', capacity: '512GB', price: 1099, originalPrice: 1199 },
    ]
  },
  // iPhone 16 Pro with variants
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/attached_assets/smartphones/iphone-16-pro.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.3" ProMotion Display',
    features: ['Apple A18 Pro chip', '6.3" LTPO OLED 120Hz', '48MP triple camera', 'Titanium design', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black Titanium', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Black Titanium', capacity: '256GB', price: 1049, originalPrice: 1149 },
      { color: 'Black Titanium', capacity: '512GB', price: 1249, originalPrice: 1349 },
      { color: 'White Titanium', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'White Titanium', capacity: '256GB', price: 1049, originalPrice: 1149 },
      { color: 'White Titanium', capacity: '512GB', price: 1249, originalPrice: 1349 },
      { color: 'Natural Titanium', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Natural Titanium', capacity: '256GB', price: 1049, originalPrice: 1149 },
      { color: 'Natural Titanium', capacity: '512GB', price: 1249, originalPrice: 1349 },
      { color: 'Desert Titanium', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Desert Titanium', capacity: '256GB', price: 1049, originalPrice: 1149 },
      { color: 'Desert Titanium', capacity: '512GB', price: 1249, originalPrice: 1349 },
    ]
  },
  // iPhone 16 with variants
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    price: 719,
    originalPrice: 799,
    discount: 10,
    image: '/attached_assets/smartphones/iphone-16.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.1" Display',
    features: ['Apple A18 chip', '6.1" OLED 60Hz', '48MP dual camera', 'Ceramic Shield', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '128GB', price: 719, originalPrice: 799 },
      { color: 'Black', capacity: '256GB', price: 809, originalPrice: 899 },
      { color: 'Black', capacity: '512GB', price: 989, originalPrice: 1099 },
      { color: 'White', capacity: '128GB', price: 719, originalPrice: 799 },
      { color: 'White', capacity: '256GB', price: 809, originalPrice: 899 },
      { color: 'White', capacity: '512GB', price: 989, originalPrice: 1099 },
      { color: 'Pink', capacity: '128GB', price: 719, originalPrice: 799 },
      { color: 'Pink', capacity: '256GB', price: 809, originalPrice: 899 },
      { color: 'Pink', capacity: '512GB', price: 989, originalPrice: 1099 },
      { color: 'Teal', capacity: '128GB', price: 719, originalPrice: 799 },
      { color: 'Teal', capacity: '256GB', price: 809, originalPrice: 899 },
      { color: 'Teal', capacity: '512GB', price: 989, originalPrice: 1099 },
      { color: 'Ultramarine', capacity: '128GB', price: 719, originalPrice: 799 },
      { color: 'Ultramarine', capacity: '256GB', price: 809, originalPrice: 899 },
      { color: 'Ultramarine', capacity: '512GB', price: 989, originalPrice: 1099 },
    ]
  },
  // iPhone 16 Plus with variants
  {
    id: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    price: 809,
    originalPrice: 899,
    discount: 10,
    image: '/attached_assets/smartphones/iphone-16-plus.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.7" Display',
    features: ['Apple A18 chip', '6.7" OLED 60Hz', '48MP dual camera', 'All-day battery', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '128GB', price: 809, originalPrice: 899 },
      { color: 'Black', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Black', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'White', capacity: '128GB', price: 809, originalPrice: 899 },
      { color: 'White', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'White', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Pink', capacity: '128GB', price: 809, originalPrice: 899 },
      { color: 'Pink', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Pink', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Teal', capacity: '128GB', price: 809, originalPrice: 899 },
      { color: 'Teal', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Teal', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Ultramarine', capacity: '128GB', price: 809, originalPrice: 899 },
      { color: 'Ultramarine', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Ultramarine', capacity: '512GB', price: 1079, originalPrice: 1199 },
    ]
  },
  // Google Pixel 10 Pro XL with variants
  {
    id: 'google-pixel-10-pro-xl',
    name: 'Google Pixel 10 Pro XL',
    price: 1079, 
    originalPrice: 1199,
    discount: 10,
    image: '/attached_assets/smartphones/google-pixel-10-pro-xl.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.8" Super Actua Display',
    features: ['Google Tensor G5', '6.8" LTPO OLED 120Hz', '50MP Pro Res Zoom 100x', '7 years updates', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Obsidian', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Obsidian', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Obsidian', capacity: '1TB', price: 1439, originalPrice: 1599 },
      { color: 'Porcelain', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Porcelain', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Porcelain', capacity: '1TB', price: 1439, originalPrice: 1599 },
      { color: 'Moonstone', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Moonstone', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Moonstone', capacity: '1TB', price: 1439, originalPrice: 1599 },
      { color: 'Jade', capacity: '256GB', price: 1079, originalPrice: 1199 },
      { color: 'Jade', capacity: '512GB', price: 1259, originalPrice: 1399 },
      { color: 'Jade', capacity: '1TB', price: 1439, originalPrice: 1599 },
    ]
  },
  // Google Pixel 9 Pro with variants
  {
    id: 'google-pixel-9-pro',
    name: 'Google Pixel 9 Pro',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/attached_assets/smartphones/google-pixel-9-pro.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.3" Super Actua Display',
    features: ['Google Tensor G4', '6.3" LTPO OLED 120Hz', '48MP triple camera', '7 years updates', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Obsidian', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Obsidian', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Obsidian', capacity: '1TB', price: 1439, originalPrice: 1599 },
      { color: 'Porcelain', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Porcelain', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Porcelain', capacity: '1TB', price: 1439, originalPrice: 1599 },
      { color: 'Hazel', capacity: '128GB', price: 899, originalPrice: 999 },
      { color: 'Hazel', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Hazel', capacity: '1TB', price: 1439, originalPrice: 1599 },
    ]
  },
  // Google Pixel 9 with variants
  {
    id: 'google-pixel-9',
    name: 'Google Pixel 9',
    price: 629,
    originalPrice: 699,
    discount: 10,
    image: '/attached_assets/smartphones/google-pixel-9.jpg',
    category: 'smartphones',
    description: 'From 128GB - 6.3" Actua Display',
    features: ['Google Tensor G4', '6.3" OLED 120Hz', '48MP dual camera', '7 years updates', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Obsidian', capacity: '128GB', price: 629, originalPrice: 699 },
      { color: 'Obsidian', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Porcelain', capacity: '128GB', price: 629, originalPrice: 699 },
      { color: 'Porcelain', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Peony', capacity: '128GB', price: 629, originalPrice: 699 },
      { color: 'Peony', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Wintergreen', capacity: '128GB', price: 629, originalPrice: 699 },
      { color: 'Wintergreen', capacity: '256GB', price: 719, originalPrice: 799 },
    ]
  },
  // Xiaomi 15 Pro with variants
  {
    id: 'xiaomi-15-pro',
    name: 'Xiaomi 15 Pro',
    price: 849,
    originalPrice: 949,
    discount: 11,
    image: '/attached_assets/smartphones/xiaomi-15-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.73" LTPO AMOLED',
    features: ['Snapdragon 8 Elite', 'Triple 50MP Leica', '6100mAh + 90W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 849, originalPrice: 949 },
      { color: 'Black', capacity: '512GB', price: 999, originalPrice: 1099 },
      { color: 'Black', capacity: '1TB', price: 1199, originalPrice: 1299 },
      { color: 'White', capacity: '256GB', price: 849, originalPrice: 949 },
      { color: 'White', capacity: '512GB', price: 999, originalPrice: 1099 },
      { color: 'White', capacity: '1TB', price: 1199, originalPrice: 1299 },
      { color: 'Titanium', capacity: '512GB', price: 999, originalPrice: 1099 },
      { color: 'Titanium', capacity: '1TB', price: 1199, originalPrice: 1299 },
    ]
  },
  // Xiaomi 15T Pro with variants
  {
    id: 'xiaomi-15t-pro',
    name: 'Xiaomi 15T Pro',
    price: 540,
    originalPrice: 600,
    discount: 10,
    image: '/attached_assets/smartphones/xiaomi-15t-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.83" OLED 144Hz',
    features: ['Dimensity 9400+', '50MP triple camera', '5500mAh + 90W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Titanium Gray', capacity: '256GB', price: 540, originalPrice: 600 },
      { color: 'Titanium Gray', capacity: '512GB', price: 630, originalPrice: 700 },
      { color: 'Titanium Gray', capacity: '1TB', price: 810, originalPrice: 900 },
      { color: 'Titanium Blue', capacity: '256GB', price: 540, originalPrice: 600 },
      { color: 'Titanium Blue', capacity: '512GB', price: 630, originalPrice: 700 },
      { color: 'Titanium Blue', capacity: '1TB', price: 810, originalPrice: 900 },
      { color: 'Titanium Black', capacity: '256GB', price: 540, originalPrice: 600 },
      { color: 'Titanium Black', capacity: '512GB', price: 630, originalPrice: 700 },
      { color: 'Titanium Black', capacity: '1TB', price: 810, originalPrice: 900 },
    ]
  },
  // Xiaomi 15T with variants
  {
    id: 'xiaomi-15t',
    name: 'Xiaomi 15T',
    price: 449,
    originalPrice: 499,
    discount: 10,
    image: '/attached_assets/smartphones/xiaomi-15t.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.83" OLED 120Hz',
    features: ['Dimensity 8400 Ultra', '50MP triple camera', '5500mAh battery', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Titan Black', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Titan Black', capacity: '512GB', price: 539, originalPrice: 599 },
      { color: 'Titan Blue', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Titan Blue', capacity: '512GB', price: 539, originalPrice: 599 },
      { color: 'Titan Gray', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Titan Gray', capacity: '512GB', price: 539, originalPrice: 599 },
    ]
  },
  // Honor Magic 7 Pro with variants
  {
    id: 'honor-magic-7-pro',
    name: 'Honor Magic 7 Pro',
    price: 1170,
    originalPrice: 1300,
    discount: 10,
    image: '/attached_assets/smartphones/honor-magic-7-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.8" LTPO OLED',
    features: ['Snapdragon 8 Elite', '200MP telephoto', '5270mAh + 100W charging', 'IP68/IP69', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Lunar Shadow Gray', capacity: '256GB', price: 1170, originalPrice: 1300 },
      { color: 'Lunar Shadow Gray', capacity: '512GB', price: 1350, originalPrice: 1500 },
      { color: 'Lunar Shadow Gray', capacity: '1TB', price: 1530, originalPrice: 1700 },
      { color: 'Breeze Blue', capacity: '256GB', price: 1170, originalPrice: 1300 },
      { color: 'Breeze Blue', capacity: '512GB', price: 1350, originalPrice: 1500 },
      { color: 'Breeze Blue', capacity: '1TB', price: 1530, originalPrice: 1700 },
      { color: 'Black', capacity: '256GB', price: 1170, originalPrice: 1300 },
      { color: 'Black', capacity: '512GB', price: 1350, originalPrice: 1500 },
      { color: 'Black', capacity: '1TB', price: 1530, originalPrice: 1700 },
    ]
  },
  // Honor Magic 6 Pro with variants
  {
    id: 'honor-magic-6-pro',
    name: 'Honor Magic 6 Pro',
    price: 1169,
    originalPrice: 1299,
    discount: 10,
    image: '/attached_assets/smartphones/honor-magic-6-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.8" LTPO OLED',
    features: ['Snapdragon 8 Gen 3', '180MP telephoto', '5600mAh + 80W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 1169, originalPrice: 1299 },
      { color: 'Black', capacity: '512GB', price: 1349, originalPrice: 1499 },
      { color: 'Black', capacity: '1TB', price: 1529, originalPrice: 1699 },
      { color: 'Epi Leather Green', capacity: '512GB', price: 1349, originalPrice: 1499 },
      { color: 'Epi Leather Green', capacity: '1TB', price: 1529, originalPrice: 1699 },
      { color: 'Meadow Green', capacity: '512GB', price: 1349, originalPrice: 1499 },
      { color: 'Meadow Green', capacity: '1TB', price: 1529, originalPrice: 1699 },
    ]
  },
  // Honor Magic 6 with variants
  {
    id: 'honor-magic-6',
    name: 'Honor Magic 6',
    price: 629,
    originalPrice: 699,
    discount: 10,
    image: '/attached_assets/smartphones/honor-magic-6.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.78" OLED',
    features: ['Snapdragon 8 Gen 3', '50MP triple camera', '5450mAh battery', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Velvet Black', capacity: '256GB', price: 629, originalPrice: 699 },
      { color: 'Velvet Black', capacity: '512GB', price: 719, originalPrice: 799 },
      { color: 'Meadow Green', capacity: '256GB', price: 629, originalPrice: 699 },
      { color: 'Meadow Green', capacity: '512GB', price: 719, originalPrice: 799 },
      { color: 'Sunrise Orange', capacity: '256GB', price: 629, originalPrice: 699 },
      { color: 'Sunrise Orange', capacity: '512GB', price: 719, originalPrice: 799 },
    ]
  },
  // Huawei Pura 80 Ultra with variants
  {
    id: 'huawei-pura-80-ultra',
    name: 'Huawei Pura 80 Ultra',
    price: 1125,
    originalPrice: 1250,
    discount: 10,
    image: '/attached_assets/smartphones/huawei-pura-80-ultra.jpg',
    category: 'smartphones',
    description: 'From 512GB - Dual Telephoto System',
    features: ['Kirin 9020', '50MP 1-inch sensor', 'Dual telephoto', '5700mAh + 100W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Gold Glaze', capacity: '512GB', price: 1125, originalPrice: 1250 },
      { color: 'Gold Glaze', capacity: '1TB', price: 1350, originalPrice: 1500 },
      { color: 'White Glaze', capacity: '512GB', price: 1125, originalPrice: 1250 },
      { color: 'White Glaze', capacity: '1TB', price: 1350, originalPrice: 1500 },
      { color: 'Black Glaze', capacity: '512GB', price: 1125, originalPrice: 1250 },
      { color: 'Black Glaze', capacity: '1TB', price: 1350, originalPrice: 1500 },
    ]
  },
  // Huawei Pura 80 Pro+ with variants
  {
    id: 'huawei-pura-80-pro-plus',
    name: 'Huawei Pura 80 Pro+',
    price: 990,
    originalPrice: 1100,
    discount: 10,
    image: '/attached_assets/smartphones/huawei-pura-80-pro-plus.jpg',
    category: 'smartphones',
    description: 'From 256GB - Premium Camera',
    features: ['Kirin 9020', '50MP 1-inch main', 'Ultra telephoto', '5700mAh + 100W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Gold Glaze', capacity: '256GB', price: 990, originalPrice: 1100 },
      { color: 'Gold Glaze', capacity: '512GB', price: 1125, originalPrice: 1250 },
      { color: 'Gold Glaze', capacity: '1TB', price: 1350, originalPrice: 1500 },
      { color: 'White Glaze', capacity: '256GB', price: 990, originalPrice: 1100 },
      { color: 'White Glaze', capacity: '512GB', price: 1125, originalPrice: 1250 },
      { color: 'White Glaze', capacity: '1TB', price: 1350, originalPrice: 1500 },
      { color: 'Black Glaze', capacity: '256GB', price: 990, originalPrice: 1100 },
      { color: 'Black Glaze', capacity: '512GB', price: 1125, originalPrice: 1250 },
      { color: 'Black Glaze', capacity: '1TB', price: 1350, originalPrice: 1500 },
    ]
  },
  // Huawei Pura 80 Pro with variants
  {
    id: 'huawei-pura-80-pro',
    name: 'Huawei Pura 80 Pro',
    price: 900,
    originalPrice: 1000,
    discount: 10,
    image: '/attached_assets/smartphones/huawei-pura-80-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - Advanced Photography',
    features: ['Kirin 9020', '50MP variable aperture', 'Telephoto with OIS', '5700mAh + 100W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Gold Glaze', capacity: '256GB', price: 900, originalPrice: 1000 },
      { color: 'Gold Glaze', capacity: '512GB', price: 1035, originalPrice: 1150 },
      { color: 'Gold Glaze', capacity: '1TB', price: 1260, originalPrice: 1400 },
      { color: 'White Glaze', capacity: '256GB', price: 900, originalPrice: 1000 },
      { color: 'White Glaze', capacity: '512GB', price: 1035, originalPrice: 1150 },
      { color: 'White Glaze', capacity: '1TB', price: 1260, originalPrice: 1400 },
      { color: 'Black Glaze', capacity: '256GB', price: 900, originalPrice: 1000 },
      { color: 'Black Glaze', capacity: '512GB', price: 1035, originalPrice: 1150 },
      { color: 'Black Glaze', capacity: '1TB', price: 1260, originalPrice: 1400 },
    ]
  },
  // Huawei Pura 80 with variants
  {
    id: 'huawei-pura-80',
    name: 'Huawei Pura 80',
    price: 765,
    originalPrice: 850,
    discount: 10,
    image: '/attached_assets/smartphones/huawei-pura-80.jpg',
    category: 'smartphones',
    description: 'From 256GB - Essential Flagship',
    features: ['Kirin 9010s', '50MP Ultra Chroma', '5.5x optical zoom', '5170mAh + 66W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Gold Glaze', capacity: '256GB', price: 765, originalPrice: 850 },
      { color: 'Gold Glaze', capacity: '512GB', price: 900, originalPrice: 1000 },
      { color: 'Gold Glaze', capacity: '1TB', price: 1080, originalPrice: 1200 },
      { color: 'White Glaze', capacity: '256GB', price: 765, originalPrice: 850 },
      { color: 'White Glaze', capacity: '512GB', price: 900, originalPrice: 1000 },
      { color: 'White Glaze', capacity: '1TB', price: 1080, originalPrice: 1200 },
      { color: 'Black Glaze', capacity: '256GB', price: 765, originalPrice: 850 },
      { color: 'Black Glaze', capacity: '512GB', price: 900, originalPrice: 1000 },
      { color: 'Black Glaze', capacity: '1TB', price: 1080, originalPrice: 1200 },
    ]
  },
  // OnePlus 15 with variants
  {
    id: 'oneplus-15',
    name: 'OnePlus 15',
    price: 719,
    originalPrice: 799,
    discount: 10,
    image: '/attached_assets/smartphones/oneplus-15.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.78" 165Hz Display',
    features: ['Snapdragon 8 Elite Gen 5', 'Triple 50MP cameras', '7000mAh + 120W charging', 'Nano-ceramic frame', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Dune', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Dune', capacity: '512GB', price: 899, originalPrice: 999 },
      { color: 'Dune', capacity: '1TB', price: 1079, originalPrice: 1199 },
      { color: 'Absolute Black', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Absolute Black', capacity: '512GB', price: 899, originalPrice: 999 },
      { color: 'Absolute Black', capacity: '1TB', price: 1079, originalPrice: 1199 },
      { color: 'Mist Purple', capacity: '256GB', price: 719, originalPrice: 799 },
      { color: 'Mist Purple', capacity: '512GB', price: 899, originalPrice: 999 },
      { color: 'Mist Purple', capacity: '1TB', price: 1079, originalPrice: 1199 },
    ]
  },
  // Asus Zenfone 12 Ultra with variants
  {
    id: 'asus-zenfone-12-ultra',
    name: 'Asus Zenfone 12 Ultra',
    price: 989,
    originalPrice: 1099,
    discount: 10,
    image: '/attached_assets/smartphones/asus-zenfone-12-ultra.jpg',
    category: 'smartphones',
    description: 'From 256GB - Gimbal Stabilization',
    features: ['Snapdragon 8 Elite', '50MP gimbal OIS', '6.78" AMOLED 144Hz', '5500mAh + 65W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Sage Green', capacity: '256GB', price: 989, originalPrice: 1099 },
      { color: 'Sage Green', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Sakura White', capacity: '256GB', price: 989, originalPrice: 1099 },
      { color: 'Sakura White', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Ebony Black', capacity: '256GB', price: 989, originalPrice: 1099 },
      { color: 'Ebony Black', capacity: '512GB', price: 1169, originalPrice: 1299 },
    ]
  },
  // Fairphone 6 with variants
  {
    id: 'fairphone-6',
    name: 'Fairphone 6',
    price: 449,
    originalPrice: 499,
    discount: 10,
    image: '/attached_assets/smartphones/fairphone-6.jpg',
    category: 'smartphones',
    description: 'From 256GB - Sustainable & Repairable',
    features: ['Snapdragon 7s Gen 3', '50MP Sony Lytia-700C', '4415mAh battery', '8 OS updates + 5yr warranty', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Matte Black', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Sky Blue', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Moss Green', capacity: '256GB', price: 449, originalPrice: 499 },
    ]
  },
  // Redmi Note 14 Pro+ 5G with variants
  {
    id: 'redmi-note-14-pro-plus',
    name: 'Redmi Note 14 Pro+ 5G',
    price: 360,
    originalPrice: 400,
    discount: 10,
    image: '/attached_assets/smartphones/redmi-note-14-pro-plus.jpg',
    category: 'smartphones',
    description: 'From 256GB - 200MP Camera',
    features: ['Snapdragon 7s Gen 3', '200MP main with OIS', '5110mAh + 120W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Sand Gold', capacity: '256GB', price: 360, originalPrice: 400 },
      { color: 'Sand Gold', capacity: '512GB', price: 432, originalPrice: 480 },
      { color: 'Midnight Black', capacity: '256GB', price: 360, originalPrice: 400 },
      { color: 'Midnight Black', capacity: '512GB', price: 432, originalPrice: 480 },
      { color: 'Frost Blue', capacity: '256GB', price: 360, originalPrice: 400 },
      { color: 'Frost Blue', capacity: '512GB', price: 432, originalPrice: 480 },
    ]
  },
  // Sony Xperia 1 VII with variants
  {
    id: 'sony-xperia-1-vii',
    name: 'Sony Xperia 1 VII',
    price: 1349,
    originalPrice: 1499,
    discount: 10,
    image: '/attached_assets/smartphones/sony-xperia-1-vii.jpg',
    category: 'smartphones',
    description: 'From 256GB - 4K 120Hz Display',
    features: ['Snapdragon 8 Elite', '6.5" 4K HDR OLED 120Hz', '52MP triple ZEISS', 'Pro camera features', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 1349, originalPrice: 1499 },
      { color: 'Black', capacity: '512GB', price: 1529, originalPrice: 1699 },
      { color: 'Black', capacity: '1TB', price: 1799, originalPrice: 1999 },
      { color: 'Khaki Green', capacity: '256GB', price: 1349, originalPrice: 1499 },
      { color: 'Khaki Green', capacity: '512GB', price: 1529, originalPrice: 1699 },
      { color: 'Khaki Green', capacity: '1TB', price: 1799, originalPrice: 1999 },
      { color: 'Platinum Silver', capacity: '256GB', price: 1349, originalPrice: 1499 },
      { color: 'Platinum Silver', capacity: '512GB', price: 1529, originalPrice: 1699 },
    ]
  },
  // OnePlus Nord 5 with variants
  {
    id: 'oneplus-nord-5',
    name: 'OnePlus Nord 5',
    price: 449,
    originalPrice: 499,
    discount: 10,
    image: '/attached_assets/smartphones/oneplus-nord-5.jpg',
    category: 'smartphones',
    description: 'From 256GB - Value Flagship',
    features: ['Snapdragon 7+ Gen 3', '6.74" AMOLED 120Hz', '50MP dual camera', '5000mAh + 80W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Aqua Surge', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Aqua Surge', capacity: '512GB', price: 539, originalPrice: 599 },
      { color: 'Misty Gray', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Misty Gray', capacity: '512GB', price: 539, originalPrice: 599 },
      { color: 'Nord Green', capacity: '256GB', price: 449, originalPrice: 499 },
      { color: 'Nord Green', capacity: '512GB', price: 539, originalPrice: 599 },
    ]
  },
  // Motorola Edge 60 Ultra with variants
  {
    id: 'motorola-edge-60-ultra',
    name: 'Motorola Edge 60 Ultra',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/attached_assets/smartphones/motorola-edge-60-ultra.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.7" Endless Edge Display',
    features: ['Snapdragon 8 Gen 3', '6.7" pOLED 165Hz', '50MP triple camera', '4800mAh + 125W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Eclipse Black', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Eclipse Black', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Eclipse Black', capacity: '1TB', price: 1259, originalPrice: 1399 },
      { color: 'Interstellar Blue', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Interstellar Blue', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Smoky Quartz', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Smoky Quartz', capacity: '512GB', price: 1079, originalPrice: 1199 },
    ]
  },
  // Realme GT 7 Pro with variants
  {
    id: 'realme-gt-7-pro',
    name: 'Realme GT 7 Pro',
    price: 899,
    originalPrice: 999,
    discount: 10,
    image: '/attached_assets/smartphones/realme-gt-7-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - Galaxy Snap Camera',
    features: ['Snapdragon 8 Elite', '50MP Sony IMX906', '6.78" LTPO AMOLED 120Hz', '6500mAh + 120W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Galaxy Grey', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Galaxy Grey', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Galaxy Grey', capacity: '1TB', price: 1259, originalPrice: 1399 },
      { color: 'Mars Orange', capacity: '256GB', price: 899, originalPrice: 999 },
      { color: 'Mars Orange', capacity: '512GB', price: 1079, originalPrice: 1199 },
      { color: 'Mars Orange', capacity: '1TB', price: 1259, originalPrice: 1399 },
    ]
  },
  // Asus Zenfone 12 with variants
  {
    id: 'asus-zenfone-12',
    name: 'Asus Zenfone 12',
    price: 629,
    originalPrice: 699,
    discount: 10,
    image: '/attached_assets/smartphones/asus-zenfone-12.jpg',
    category: 'smartphones',
    description: 'From 256GB - Compact Flagship',
    features: ['Snapdragon 8 Gen 3', '5.9" AMOLED 144Hz', '50MP triple camera', 'Compact & lightweight', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Midnight Black', capacity: '256GB', price: 629, originalPrice: 699 },
      { color: 'Midnight Black', capacity: '512GB', price: 719, originalPrice: 799 },
      { color: 'Horizon Silver', capacity: '256GB', price: 629, originalPrice: 699 },
      { color: 'Horizon Silver', capacity: '512GB', price: 719, originalPrice: 799 },
      { color: 'Aurora Green', capacity: '256GB', price: 629, originalPrice: 699 },
      { color: 'Aurora Green', capacity: '512GB', price: 719, originalPrice: 799 },
    ]
  },
  // === GAMING SMARTPHONES ===
  // Asus ROG Phone 9 Pro with variants
  {
    id: 'asus-rog-phone-9-pro',
    name: 'Asus ROG Phone 9 Pro',
    price: 1169,
    originalPrice: 1299,
    discount: 10,
    image: '/attached_assets/smartphones/asus-rog-phone-9-pro.jpg',
    category: 'smartphones',
    description: 'From 512GB - Elite Gaming Phone',
    features: ['Snapdragon 8 Elite', 'AniMe Vision display', '6.78" LTPO 185Hz', '5800mAh battery', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Phantom Black', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Phantom Black', capacity: '1TB', price: 1439, originalPrice: 1599 },
    ]
  },
  // Asus ROG Phone 9 with variants
  {
    id: 'asus-rog-phone-9',
    name: 'Asus ROG Phone 9',
    price: 989,
    originalPrice: 1099,
    discount: 10,
    image: '/attached_assets/smartphones/asus-rog-phone-9.jpg',
    category: 'smartphones',
    description: 'From 256GB - Gaming Performance',
    features: ['Snapdragon 8 Elite', 'AirTrigger buttons', '6.78" LTPO 185Hz', '5800mAh battery', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Phantom Black', capacity: '256GB', price: 989, originalPrice: 1099 },
      { color: 'Phantom Black', capacity: '512GB', price: 1169, originalPrice: 1299 },
      { color: 'Storm White', capacity: '256GB', price: 989, originalPrice: 1099 },
      { color: 'Storm White', capacity: '512GB', price: 1169, originalPrice: 1299 },
    ]
  },
  // Lenovo Legion Phone with variants
  {
    id: 'lenovo-legion-phone',
    name: 'Lenovo Legion Phone',
    price: 809,
    originalPrice: 899,
    discount: 10,
    image: '/attached_assets/smartphones/lenovo-legion-phone.jpg',
    category: 'smartphones',
    description: '512GB - Side Pop-up Camera',
    features: ['Snapdragon 8 Gen 3', 'Side pop-up camera', '6.78" AMOLED 144Hz', '5000mAh + 68W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Titanium White', capacity: '512GB', price: 809, originalPrice: 899 },
      { color: 'Ultimate Black', capacity: '512GB', price: 809, originalPrice: 899 },
    ]
  },
  // Nubia RedMagic 10 Pro with variants
  {
    id: 'nubia-redmagic-10-pro',
    name: 'Nubia RedMagic 10 Pro',
    price: 552,
    originalPrice: 613,
    discount: 10,
    image: '/attached_assets/smartphones/nubia-redmagic-10-pro.jpg',
    category: 'smartphones',
    description: 'From 256GB - Active Cooling',
    features: ['Snapdragon 8 Elite', 'Built-in cooling fan', '6.85" AMOLED 144Hz', '7050mAh + 100W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Snowfall', capacity: '256GB', price: 552, originalPrice: 613 },
      { color: 'Snowfall', capacity: '512GB', price: 675, originalPrice: 750 },
      { color: 'Snowfall', capacity: '1TB', price: 900, originalPrice: 1000 },
      { color: 'Deuterium', capacity: '256GB', price: 552, originalPrice: 613 },
      { color: 'Deuterium', capacity: '512GB', price: 675, originalPrice: 750 },
      { color: 'Deuterium', capacity: '1TB', price: 900, originalPrice: 1000 },
      { color: 'Shadowblade', capacity: '256GB', price: 552, originalPrice: 613 },
      { color: 'Shadowblade', capacity: '512GB', price: 675, originalPrice: 750 },
      { color: 'Shadowblade', capacity: '1TB', price: 900, originalPrice: 1000 },
    ]
  },
  // Nubia RedMagic 10 Air 5G with variants
  {
    id: 'nubia-redmagic-10-air',
    name: 'Nubia RedMagic 10 Air 5G',
    price: 494,
    originalPrice: 549,
    discount: 10,
    image: '/attached_assets/smartphones/nubia-redmagic-10-air.jpg',
    category: 'smartphones',
    description: 'From 256GB - Ultra-thin Gaming',
    features: ['Snapdragon 8 Gen 3', 'Thinner design', '6.8" AMOLED 120Hz', '6000mAh + 80W charging', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Twilight', capacity: '256GB', price: 494, originalPrice: 549 },
      { color: 'Twilight', capacity: '512GB', price: 629, originalPrice: 699 },
      { color: 'Hailstone', capacity: '256GB', price: 494, originalPrice: 549 },
      { color: 'Hailstone', capacity: '512GB', price: 629, originalPrice: 699 },
      { color: 'Flare', capacity: '256GB', price: 494, originalPrice: 549 },
      { color: 'Flare', capacity: '512GB', price: 629, originalPrice: 699 },
    ]
  },
  // Xiaomi 14T with variants
  {
    id: 'xiaomi-14t',
    name: 'Xiaomi 14T',
    price: 372,
    originalPrice: 537,
    discount: 31,
    image: '/assets/stock_images/xiaomi_15_standard_s_12e3b53c.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.67" AMOLED Display',
    features: ['Dimensity 8300 Ultra', '50MP Leica triple camera', '5000mAh + 67W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Titan Black', capacity: '256GB', price: 372, originalPrice: 537 },
      { color: 'Titan Black', capacity: '512GB', price: 445, originalPrice: 645 },
      { color: 'Titan Blue', capacity: '256GB', price: 372, originalPrice: 537 },
      { color: 'Titan Blue', capacity: '512GB', price: 445, originalPrice: 645 },
      { color: 'Titan Gray', capacity: '256GB', price: 372, originalPrice: 537 },
      { color: 'Titan Gray', capacity: '512GB', price: 445, originalPrice: 645 },
    ]
  },
  // Xiaomi 14T Pro with variants
  {
    id: 'xiaomi-14t-pro',
    name: 'Xiaomi 14T Pro',
    price: 496,
    originalPrice: 661,
    discount: 25,
    image: '/assets/stock_images/premium_smartphones__d234c20f.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.67" AMOLED 144Hz',
    features: ['Dimensity 9300+', '50MP Leica triple camera', '5000mAh + 120W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Titan Black', capacity: '256GB', price: 496, originalPrice: 661 },
      { color: 'Titan Black', capacity: '512GB', price: 661, originalPrice: 744 },
      { color: 'Titan Black', capacity: '1TB', price: 744, originalPrice: 826 },
      { color: 'Titan Blue', capacity: '256GB', price: 496, originalPrice: 661 },
      { color: 'Titan Blue', capacity: '512GB', price: 661, originalPrice: 744 },
      { color: 'Titan Blue', capacity: '1TB', price: 744, originalPrice: 826 },
      { color: 'Titan Gray', capacity: '256GB', price: 496, originalPrice: 661 },
      { color: 'Titan Gray', capacity: '512GB', price: 661, originalPrice: 744 },
      { color: 'Titan Gray', capacity: '1TB', price: 744, originalPrice: 826 },
    ]
  },
  // Xiaomi 14 with variants
  {
    id: 'xiaomi-14',
    name: 'Xiaomi 14',
    price: 744,
    originalPrice: 909,
    discount: 18,
    image: '/assets/stock_images/premium_smartphones__b651af0a.jpg',
    category: 'smartphones',
    description: 'From 256GB - 6.36" LTPO AMOLED',
    features: ['Snapdragon 8 Gen 3', 'Triple 50MP Leica', '4610mAh + 90W charging', 'IP68', 'Free shipping'],
    hasVariants: true,
    variants: [
      { color: 'Black', capacity: '256GB', price: 744, originalPrice: 909 },
      { color: 'Black', capacity: '512GB', price: 827, originalPrice: 1009 },
      { color: 'White', capacity: '256GB', price: 744, originalPrice: 909 },
      { color: 'White', capacity: '512GB', price: 827, originalPrice: 1009 },
      { color: 'Jade Green', capacity: '256GB', price: 744, originalPrice: 909 },
      { color: 'Jade Green', capacity: '512GB', price: 827, originalPrice: 1009 },
    ]
  },

  // === SMARTWATCHES (16 products) ===
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    price: 799,
    originalPrice: 899,
    discount: 11,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: '49mm, Ocean Band',
    features: ['Titanium case', 'Extended battery', 'Action button', 'Free shipping']
  },
  {
    id: 'galaxy-watch-6-classic',
    name: 'Galaxy Watch 6 Classic',
    price: 399,
    originalPrice: 499,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: '47mm, Black',
    features: ['Rotating bezel', 'Sleep tracking', 'Wear OS', 'Free shipping']
  },
  {
    id: 'garmin-fenix-7x',
    name: 'Garmin Fenix 7X',
    price: 699,
    originalPrice: 799,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Solar, Sapphire',
    features: ['Multi-sport GPS', 'Solar charging', 'Rugged design', 'Free shipping']
  },
  {
    id: 'fitbit-sense-2',
    name: 'Fitbit Sense 2',
    price: 249,
    originalPrice: 299,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Health focused',
    features: ['Stress management', 'ECG app', 'GPS built-in', 'Free shipping']
  },
  {
    id: 'suunto-9-peak-pro',
    name: 'Suunto 9 Peak Pro',
    price: 549,
    originalPrice: 649,
    discount: 15,
    image: 'https://images.unsplash.com/photo-1594736797933-d0cc01e17207?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Titanium, GPS',
    features: ['Adventure ready', 'Long battery', 'Offline maps', 'Free shipping']
  },
  {
    id: 'polar-grit-x2-pro',
    name: 'Polar Grit X2 Pro',
    price: 499,
    originalPrice: 599,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Titan, Sapphire',
    features: ['Military-grade durability', 'Training guidance', 'Recovery insights', 'Free shipping']
  },
  {
    id: 'coros-vertix-2s',
    name: 'COROS Vertix 2S',
    price: 599,
    originalPrice: 699,
    discount: 14,
    image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Adventure GPS',
    features: ['60-day battery', 'Dual-frequency GPS', 'Mountain ready', 'Free shipping']
  },
  {
    id: 'amazfit-t-rex-3',
    name: 'Amazfit T-Rex 3',
    price: 199,
    originalPrice: 249,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Rugged GPS',
    features: ['Military standard', 'Long battery life', 'Health tracking', 'Free shipping']
  },
  {
    id: 'huawei-watch-gt-4',
    name: 'Huawei Watch GT 4',
    price: 249,
    originalPrice: 299,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: '46mm, Sport',
    features: ['2-week battery', 'Fitness tracking', 'Smart features', 'Free shipping']
  },
  {
    id: 'fossil-gen-6-wellness',
    name: 'Fossil Gen 6 Wellness',
    price: 199,
    originalPrice: 259,
    discount: 23,
    image: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Wear OS 3',
    features: ['Wellness focused', 'Google Assistant', 'Fast charging', 'Free shipping']
  },
  {
    id: 'ticwatch-pro-5',
    name: 'TicWatch Pro 5',
    price: 349,
    originalPrice: 399,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1544117519-31a4b719223d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Snapdragon W5',
    features: ['Dual display', 'Wear OS 3', 'Long battery', 'Free shipping']
  },
  {
    id: 'withings-scanwatch-2',
    name: 'Withings ScanWatch 2',
    price: 349,
    originalPrice: 399,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Hybrid smartwatch',
    features: ['Medical-grade sensors', 'Classic design', '30-day battery', 'Free shipping']
  },
  {
    id: 'casio-g-shock-gbx100',
    name: 'Casio G-Shock GBX100',
    price: 399,
    originalPrice: 449,
    discount: 11,
    image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Tough Solar',
    features: ['G-Shock durability', 'Tide graph', 'Phone finder', 'Free shipping']
  },
  {
    id: 'tag-heuer-connected',
    name: 'TAG Heuer Connected',
    price: 1799,
    originalPrice: 1999,
    discount: 10,
    image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Luxury smartwatch',
    features: ['Swiss luxury', 'Titanium case', 'Premium materials', 'Free shipping']
  },
  {
    id: 'xiaomi-watch-s3',
    name: 'Xiaomi Watch S3',
    price: 149,
    originalPrice: 199,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'AMOLED display',
    features: ['12-day battery', 'Health monitoring', 'Always-on display', 'Free shipping']
  },
  {
    id: 'oura-ring-gen3',
    name: 'Oura Ring Gen3',
    price: 299,
    originalPrice: 349,
    discount: 14,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'watches',
    description: 'Smart ring',
    features: ['Sleep tracking', 'Recovery insights', 'Discreet design', 'Free shipping']
  },

  // === SNEAKERS (12 products) ===
  {
    id: 'air-jordan-4-retro',
    name: 'Air Jordan 4 Retro',
    price: 219,
    originalPrice: 259,
    discount: 15,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'White Cement',
    features: ['Classic silhouette', 'Premium leather', 'Basketball heritage', 'Free shipping']
  },
  {
    id: 'yeezy-boost-350-v2',
    name: 'Yeezy Boost 350 V2',
    price: 249,
    originalPrice: 299,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Bone',
    features: ['Boost technology', 'Primeknit upper', 'Iconic design', 'Free shipping']
  },
  {
    id: 'nike-dunk-low',
    name: 'Nike Dunk Low',
    price: 119,
    originalPrice: 149,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Panda',
    features: ['Retro basketball', 'Versatile style', 'Premium materials', 'Free shipping']
  },
  {
    id: 'new-balance-990v6',
    name: 'New Balance 990v6',
    price: 199,
    originalPrice: 229,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1506629905460-e6eaec17cff0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Gray',
    features: ['Made in USA', 'Premium comfort', 'Classic design', 'Free shipping']
  },
  {
    id: 'adidas-ultraboost-22',
    name: 'Adidas Ultraboost 22',
    price: 179,
    originalPrice: 219,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1586316237874-40a3b3d24e34?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Core Black',
    features: ['Boost midsole', 'Primeknit upper', 'Energy return', 'Free shipping']
  },
  {
    id: 'converse-chuck-70',
    name: 'Converse Chuck 70',
    price: 89,
    originalPrice: 109,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1597048122608-8ad69e6f8d96?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'High Top',
    features: ['Vintage style', 'Premium canvas', 'Timeless design', 'Free shipping']
  },
  {
    id: 'vans-old-skool',
    name: 'Vans Old Skool',
    price: 69,
    originalPrice: 89,
    discount: 22,
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Black/White',
    features: ['Skate heritage', 'Waffle outsole', 'Iconic stripe', 'Free shipping']
  },
  {
    id: 'puma-suede-classic',
    name: 'Puma Suede Classic',
    price: 79,
    originalPrice: 99,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Peacoat',
    features: ['Suede upper', 'Classic formstrip', 'Retro style', 'Free shipping']
  },
  {
    id: 'asics-gel-kayano-30',
    name: 'ASICS Gel-Kayano 30',
    price: 159,
    originalPrice: 189,
    discount: 16,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Running shoe',
    features: ['Stability running', 'Gel cushioning', 'FlyteFoam', 'Free shipping']
  },
  {
    id: 'on-cloudstratus-3',
    name: 'On Cloudstratus 3',
    price: 169,
    originalPrice: 199,
    discount: 15,
    image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Maximalist running',
    features: ['CloudTec cushioning', 'Swiss engineering', 'Premium comfort', 'Free shipping']
  },
  {
    id: 'hoka-clifton-9',
    name: 'Hoka Clifton 9',
    price: 139,
    originalPrice: 169,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Neutral running',
    features: ['Maximum cushioning', 'Lightweight', 'Everyday comfort', 'Free shipping']
  },
  {
    id: 'allbirds-tree-runners',
    name: 'Allbirds Tree Runners',
    price: 98,
    originalPrice: 118,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'sneakers',
    description: 'Natural White',
    features: ['Sustainable materials', 'Tree fiber', 'Comfortable', 'Free shipping']
  },

  // === GADGETS (12 products) ===
  {
    id: 'smart-robot-vacuum-pro',
    name: 'Smart Robot Vacuum Pro',
    price: 449,
    originalPrice: 549,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Auto-mapping, App Control',
    features: ['LiDAR navigation', 'Self-emptying', 'App control', 'Free delivery']
  },
  {
    id: 'dyson-air-purifier-tp07',
    name: 'Dyson Air Purifier TP07',
    price: 549,
    originalPrice: 649,
    discount: 15,
    image: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'HEPA Filter, WiFi Enabled',
    features: ['HEPA filtration', 'Real-time air quality', 'Dyson technology', 'Free delivery']
  },
  {
    id: 'sonos-one-gen2',
    name: 'Sonos One Gen2',
    price: 199,
    originalPrice: 249,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Smart Speaker',
    features: ['Voice control', 'Hi-Fi sound', 'Multi-room audio', 'Free delivery']
  },
  {
    id: 'philips-hue-starter-kit',
    name: 'Philips Hue Starter Kit',
    price: 149,
    originalPrice: 199,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1524634126442-357e0eac3c14?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Smart lighting',
    features: ['16 million colors', 'Voice control', 'App control', 'Free delivery']
  },
  {
    id: 'nest-thermostat',
    name: 'Google Nest Thermostat',
    price: 129,
    originalPrice: 169,
    discount: 24,
    image: 'https://images.unsplash.com/photo-1558089687-5a7b3a3e4d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Smart home control',
    features: ['Energy saving', 'Voice control', 'Remote access', 'Free delivery']
  },
  {
    id: 'ring-video-doorbell-pro',
    name: 'Ring Video Doorbell Pro',
    price: 179,
    originalPrice: 229,
    discount: 22,
    image: 'https://images.unsplash.com/photo-1556302487-0e97e34fa26e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Home security',
    features: ['1080p HD video', 'Two-way talk', 'Motion detection', 'Free delivery']
  },
  {
    id: 'anker-power-bank-737',
    name: 'Anker Power Bank 737',
    price: 149,
    originalPrice: 179,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1625945277632-0ebf1c0db4e4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: '24000mAh capacity',
    features: ['140W output', 'Fast charging', 'Multiple ports', 'Free delivery']
  },
  {
    id: 'bose-quietcomfort-45',
    name: 'Bose QuietComfort 45',
    price: 279,
    originalPrice: 329,
    discount: 15,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Wireless headphones',
    features: ['Active noise cancellation', 'Premium sound', '24h battery', 'Free delivery']
  },
  {
    id: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    price: 349,
    originalPrice: 399,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Premium headphones',
    features: ['Industry-leading ANC', 'LDAC codec', '30h battery', 'Free delivery']
  },
  {
    id: 'amazon-echo-show-15',
    name: 'Amazon Echo Show 15',
    price: 249,
    originalPrice: 299,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Smart display',
    features: ['15.6" Full HD', 'Alexa built-in', 'Smart home hub', 'Free delivery']
  },
  {
    id: 'dji-mini-4-pro',
    name: 'DJI Mini 4 Pro',
    price: 759,
    originalPrice: 899,
    discount: 16,
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Compact drone',
    features: ['4K HDR video', 'Obstacle avoidance', 'Long flight time', 'Free delivery']
  },
  {
    id: 'gopro-hero-12-black',
    name: 'GoPro HERO12 Black',
    price: 349,
    originalPrice: 399,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1590179068383-b9c69aacebd3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'gadgets',
    description: 'Action camera',
    features: ['5.3K video', 'HyperSmooth 6.0', 'Waterproof', 'Free delivery']
  },

  // === URBAN MOBILITY (12 products) ===
  {
    id: 'xiaomi-electric-scooter-4-ultra',
    name: 'Xiaomi Electric Scooter 4 Ultra',
    price: 649,
    originalPrice: 749,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1559311320-36b8d171c6e5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '70km range',
    features: ['25 km/h max speed', '70km range', 'Dual braking system', 'Free shipping']
  },
  {
    id: 'segway-ninebot-max-g2',
    name: 'Segway Ninebot Max G2',
    price: 799,
    originalPrice: 899,
    discount: 11,
    image: 'https://images.unsplash.com/photo-1585748347325-d0f4db2f7b11?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '70km range',
    features: ['30 km/h max speed', '70km range', 'Self-healing tires', 'Free shipping']
  },
  {
    id: 'electric-bike-vanmoof-s5',
    name: 'VanMoof S5 E-Bike',
    price: 2299,
    originalPrice: 2599,
    discount: 12,
    image: 'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '150km range',
    features: ['32 km/h assisted', '150km range', 'Anti-theft tracking', 'Free shipping']
  },
  {
    id: 'cowboy-4-st-ebike',
    name: 'Cowboy 4 ST E-Bike',
    price: 2190,
    originalPrice: 2490,
    discount: 12,
    image: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '70km range',
    features: ['25 km/h assisted', '70km range', 'Connected app', 'Free shipping']
  },
  {
    id: 'ninebot-kickscooter-f2-pro',
    name: 'Ninebot KickScooter F2 Pro',
    price: 549,
    originalPrice: 629,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '55km range',
    features: ['25 km/h max speed', '55km range', 'IPX5 water resistant', 'Free shipping']
  },
  {
    id: 'super73-s2-ebike',
    name: 'Super73 S2 E-Bike',
    price: 2495,
    originalPrice: 2795,
    discount: 11,
    image: 'https://images.unsplash.com/photo-1559911567-88ba57e5e15a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '120km range',
    features: ['32 km/h max speed', '120km range', 'Retro design', 'Free shipping']
  },
  {
    id: 'pure-air-pro-scooter',
    name: 'Pure Air Pro Scooter',
    price: 449,
    originalPrice: 499,
    discount: 10,
    image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '50km range',
    features: ['25 km/h max speed', '50km range', 'Foldable design', 'Free shipping']
  },
  {
    id: 'rad-power-bikes-radrunner-3',
    name: 'Rad Power RadRunner 3',
    price: 1899,
    originalPrice: 2099,
    discount: 10,
    image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '72km range',
    features: ['32 km/h assisted', '72km range', 'Cargo ready', 'Free shipping']
  },
  {
    id: 'xiaomi-mi-scooter-3-lite',
    name: 'Xiaomi Mi Scooter 3 Lite',
    price: 349,
    originalPrice: 399,
    discount: 13,
    image: 'https://images.unsplash.com/photo-1600796603940-76c6c06c7fdd?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '20km range',
    features: ['20 km/h max speed', '20km range', 'Lightweight 13kg', 'Free shipping']
  },
  {
    id: 'tern-vektron-q9-folding',
    name: 'Tern Vektron Q9 Folding',
    price: 3299,
    originalPrice: 3699,
    discount: 11,
    image: 'https://images.unsplash.com/photo-1544191696-102dbdaeefc0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '100km range',
    features: ['25 km/h assisted', '100km range', 'Folds compact', 'Free shipping']
  },
  {
    id: 'inokim-quick-4-super',
    name: 'Inokim Quick 4 Super',
    price: 1199,
    originalPrice: 1349,
    discount: 11,
    image: 'https://images.unsplash.com/photo-1623312781503-2a24e03e0013?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '65km range',
    features: ['30 km/h max speed', '65km range', 'Premium build', 'Free shipping']
  },
  {
    id: 'gogoro-eeyo-1s-ebike',
    name: 'Gogoro Eeyo 1S E-Bike',
    price: 4299,
    originalPrice: 4799,
    discount: 10,
    image: 'https://images.unsplash.com/photo-1617912734022-51e762ac8d18?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    category: 'mobility',
    description: '90km range',
    features: ['25 km/h assisted', '90km range', 'Carbon fiber frame', 'Free shipping']
  },
];

export function getProductsByCategory(category: string): Product[] {
  return products.filter(product => product.category === category);
}
